sudo: false
language: node_js
node_js:
- "0.10"
branches:
 only:
- master
- testing
cache:
  directories:
  - node_modules
os: 
- linux
dist: xenial
before_install:
- npm update
install:
- npm install
script:
- npm test
