name: Compatibility Issue
description: Report compatibility issue for a certain browser.
title: "<Compatibility - [OS] [Browser] - [What is not working]>"
labels: [compatibility]
body:
- type: textarea
  attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is( What is not working and what is expected).
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment (Describe the browser).
    description:  OS [e.g. iOS, Android, MacOs or Windows] --> Browser [e.g. chrome, safari, edge, firefox] --> Version [e.g. 22]
  validations:
    required: true 
- type: textarea
  attributes:
    label: Screenshots.
    description: If applicable, add screenshots to help explain your problem.
  validations:
    required: false     
- type: textarea
  attributes:
    label: Additional context.
    description: Add any other context about the problem here.
  validations:
    required: false      